###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    memcached:
      image: memcached:alpine
      container_name: sagu-api-memcached

    webserver:
      image: nginx:alpine
      container_name: sagu-api-webserver
      working_dir: /var/www
      volumes:
          - .:/var/www
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8085:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: sagu-api-php-fpm
      working_dir: /var/www
      volumes:
        - .:/var/www
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini

